environment: dev
redis:
   host: redis
   port: 6379
mongo:
   master:
      hostname: mongo
      port: 27017
      database: mytest
stripe:
   endpointSecert: hello
logger:
   host: logger
   port: 24224
